### ISSUE TITLE
Tiny-Imagenet

### ISSUE THREAD

**Issue by mlosch** [klasleino/gloro#2]
Hi, first of all thanks for publishing your code!
I tried to reproduce your tiny-imagenet results, yet have stumbled across dataset formatting issues.
In https://github.com/klasleino/gloro/blob/5ebfe0f3850bca20e4ee4414fa2ee8a4af303023/tools/training/utils.py#L103 a dataset is requested named "TinyImagenet_train_x.npy".
I have not come across this type of format and I don't see any scripts in your repo to produce these files.
Could you provide a script that preprocesses the formatting from "http://cs231n.stanford.edu/tiny-imagenet-200.zip"?

Thanks in advance!

**Comment by klasleino** [comment]
Hi Max, I apologize for the slow response. I don't know if I have a script around for processing the original files, but perhaps better is I can add a link directly to the `.npy` files we used---no preprocessing necessary.

I've uploaded the files [here](https://drive.google.com/file/d/1YuaNDNgHDW1hhIajKCZ6a8symm3-niCh/view?usp=sharing).

To use, unzip the directory to a location of your choice and then set the `"TINY_IMAGENET_LOCATION"` environment variable to point to the unzipped directory.

Hope this helps!
